server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springlearn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# Specify the DBMS
  jpa:
     database: MYSQL
# Show or not log for each sql query
     show-sql: true
    #  generate-ddl: true
# Hibernate ddl auto (create, create-drop, update)
     hibernate:
       ddl-auto: update
  main:
    allow-bean-definition-overriding: true 
